export enum PermissionsEnum {
  READ_MAIN_PAGE = 'READ_MAIN_PAGE',

  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  READ_ORGANIZATION = 'READ_ORGANIZATION',
  UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',

  CREATE_INVOICE = 'CREATE_INVOICE',
  READ_INVOICE = 'READ_INVOICE',
  UPDATE_INVOICE = 'UPDATE_INVOICE',
  DELETE_INVOICE = 'DELETE_INVOICE',

  CREATE_ADMIN_SETTINGS = 'CREATE_ADMIN_SETTINGS',
  READ_ADMIN_SETTINGS = 'READ_ADMIN_SETTINGS',
  UPDATE_ADMIN_SETTINGS = 'UPDATE_ADMIN_SETTINGS',
  DELETE_ADMIN_SETTINGS = 'DELETE_ADMIN_SETTINGS',

  CREATE_ARTICLES = 'CREATE_ARTICLES',
  READ_ARTICLES = 'READ_ARTICLES',
  UPDATE_ARTICLES = 'UPDATE_ARTICLES',
  DELETE_ARTICLES = 'DELETE_ARTICLES',

  CREATE_SOFT_SETTINGS = 'CREATE_SOFT_SETTINGS',
  READ_SOFT_SETTINGS = 'READ_SOFT_SETTINGS',
  UPDATE_SOFT_SETTINGS = 'UPDATE_SOFT_SETTINGS',
  DELETE_SOFT_SETTINGS = 'DELETE_SOFT_SETTINGS',

  CREATE_SPECIFIC_ORGANIZATION = 'CREATE_SPECIFIC_ORGANIZATION',
  READ_SPECIFIC_ORGANIZATION = 'READ_SPECIFIC_ORGANIZATION',
  UPDATE_SPECIFIC_ORGANIZATION = 'UPDATE_SPECIFIC_ORGANIZATION',
  DELETE_SPECIFIC_ORGANIZATION = 'DELETE_SPECIFIC_ORGANIZATION',
}
