export enum PermissionsEnum {
  READ_MAIN_PAGE = 'READ_MAIN_PAGE',
  READ_ORGANIZATION = 'READ_ORGANIZATION',
  READ_INVOICE = 'READ_INVOICE',
  READ_ADMIN_SETTINGS = 'READ_ADMIN_SETTINGS',
  UPDATE_ARTICLES = 'UPDATE_ARTICLES',
  READ_SOFT_SETTINGS = 'READ_SOFT_SETTINGS',
}
